#!/bin/bash

echo "=========================================="
echo "🧪 TESTE MEDIA API"
echo "=========================================="
echo ""

echo "WICHTIG: Du brauchst dein Auth-Token!"
echo ""
echo "So holst du es:"
echo "1. Öffne: https://start.shopmarkets.app"
echo "2. Drücke F12 (Developer Tools)"
echo "3. Gehe zu: Application → Local Storage → https://start.shopmarkets.app"
echo "4. Kopiere den Wert von 'auth_token'"
echo ""
echo "Dann führe aus:"
echo ""
echo "export AUTH_TOKEN='<dein_token_hier>'"
echo ""
echo "curl -H \"Authorization: Bearer \$AUTH_TOKEN\" \\"
echo "  https://api.shopmarkets.app/api/media"
echo ""
echo "=========================================="
echo ""
echo "Erwartetes Ergebnis:"
echo "JSON-Array mit 7 Dateien"
echo ""
echo "Falls leer ([]):"
echo "- user_id stimmt nicht überein"
echo "- is_active = false"
echo "- Authentifizierung fehlgeschlagen"
echo ""
echo "Falls 401/403:"
echo "- Token ungültig oder abgelaufen"
echo "- JWT_SECRET stimmt nicht überein"
echo ""
